---
title: "Survival Sire Model"
author: "Enoch Ng'oma"
date: "3/7/2017"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Setup

```{r}
library(MCMCglmm)
library(tidyverse)

source("h2life_load_data.R")
```

## Ingleby et al Model

```{r eval=FALSE}
library(MCMCglmm)
data<-read.table("gxe.txt",
                 h = T,
                 colClasses = c("numeric", rep("factor",4), rep("numeric",3)))
attach(data)
str(data)

males<-data[Sex=="M",]
females<-data[Sex=="F",]

fam <- rep("gaussian",3)
                         
## male model: CHCs ~ Food*Temp + Food*Isoline + Temp*Isoline ; DIC 14968.1

prior.10 <- list(R = list(V = diag(3) / 3, nu = 0.02),
                 G = list(G1 = list(V = diag(9) / 9, nu = 0.02)))

fmla.10 <- as.formula(
  paste("cbind(PC1, PC2, PC3)" ,
        "~",
        "trait + trait:Temperature + trait:Food + trait:Food:Temperature - 1"))

m.10 <- MCMCglmm(fmla.10,
                 random =~ idh(trait + trait:Food + trait:Temperature):Isoline,
                 rcov =~ idh(trait):units, 
                 prior =  prior.10,
                 data = males,
                 family = fam,
                 nitt = 200000,
                 burnin = 10000,
                 thin = 30,
                 pr = F)

## genetic correlation               
corr <- m.10$VCV[ , 4] / (sqrt(m.10$VCV[ , 1] * m.10$VCV[ , 22]))
summary(corr)

## heritability
h2<-2*m.10$VCV[,4]/(m.10$VCV[,1]+m.10$VCV[,22])
summary(h2)
                
## female model: CHCs ~ Food*Temp + Food*Isoline + Temp*Isoline ; DIC 13903.59

prior.9 <- list(R = list(V = diag(3) / 3, nu = 0.02),
                G = list(G1 = list(V = diag(9) / 9, nu = 0.02)))
fmla.9 <- as.formula(
  paste("cbind(PC1, PC2, PC3)",
        "~",
        "trait + trait:Temperature + trait:Food + trait:Food:Temperature -1"))
f.9 <- MCMCglmm(fmla.9,
                random =~ idh(trait + trait:Temperature + trait:Food):Isoline,
                rcov =~ idh(trait):units,
                prior =  prior.9,
                data = females,
                family = fam,
                nitt = 200000,
                burnin = 10000,
                thin = 30,
                pr = F)
             
## genetic correlation               
corr<-f.9$VCV[,4]/(sqrt(f.9$VCV[,1]*f.9$VCV[,22]))
summary(corr)

## heritability
h2<-2*f.9$VCV[,4]/(f.9$VCV[,1]+f.9$VCV[,22])
summary(h2)
```

# Sire model MCMCglmm

FIXME

```{r}
library(parallel)

set.seed(52329487)
iter <- 800000
burnin <- iter * 0.1
thinning <- 200
chains <- 1

prior <- list(R = list(V = 1, nu = 0.002),
              G = list(G1 = list(V = 1, nu = 0.002),
                       G2 = list(V = 1, nu = 0.002),
                       G3 = list(V = diag(3), nu = 0.002)))

# parameter extension
prior_ext <- list(
  R = list(V = 1, nu = 0.002),
  G = list(G1 = list(V = 1, nu = 0.002, alpha.mu = 0, alpha.V = 1000),
           G2 = list(V = 1, nu = 0.002, alpha.mu = 0, alpha.V = 1000),
           G3 = list(V = diag(3), nu = 0.002,
                     alpha.mu = c(0, 0, 0),
                     alpha.V = diag(3) * 1000)))

system.time({
  m6 <- mclapply(1:chains, function(i) {
    MCMCglmm(NewAge ~ treat - 1, 
             random = ~ sire + sire:dam + idh(treat):sire,
             rcov = ~ idh(treat):sire,
             family = "gaussian",
             prior = prior_ext,
             data = h2life,
             nitt = iter,
             burnin = burnin,
             thin = thinning)
  }, mc.cores = chains)
})

save(m6, file = "Sire_model.Rda")

# Load model & process ########################################

load("Sire_model.Rda")

m1 <- m6[[1]]

fe <- lapply(m6, function(m) m$Sol)
fe <- do.call(mcmc.list, fe)
plot(fe, ask = FALSE)

re <- lapply(m6, function(m) m$VCV)
re <- do.call(mcmc.list, re)
plot(re, ask = FALSE)

# Fixed
autocorr.diag(fe)
effectiveSize(fe)

# Random
autocorr.diag(re)
effectiveSize(re)

re <- as.mcmc(as.matrix(re))
```

## Sire model comparison

```{r}
iter <- 4000000
burnin <- 50000
thinning <- 200

V_mat <- diag(3)

sire_full_us <- MCMCglmm(
  NewAge ~ treat - 1,
  random = ~ sire + sire:dam + us(treat):sire,
  prior = list(R = list(V = 1, nu = 0.002),
               G = list(G1 = list(V = 1, nu = 0.002),
                        G2 = list(V = 1, nu = 0.002),
                        G3 = list(V = V_mat, nu = 1.002))),
  data = h2life,
  nitt = iter,
  burnin = burnin,
  thin = thinning)
save(sire_full_us, file = "sire_full_us.RDA")

sire_full <- MCMCglmm(
  NewAge ~ treat - 1,
  random = ~ sire + sire:dam + treat:sire,
  prior = list(R = list(V = 1, nu = 0.002),
               G = list(G1 = list(V = 1, nu = 0.002),
                        G2 = list(V = 1, nu = 0.002),
                        G3 = list(V = 1, nu = 0.002))),
  data = h2life,
  nitt = iter,
  burnin = burnin,
  thin = thinning)

sire_rest <- MCMCglmm(
  NewAge ~ treat - 1, 
  random = ~ sire + sire:dam,
  prior = list(R = list(V = 1, nu = 0.002),
               G = list(G1 = list(V = 1, nu = 0.002),
                        G2 = list(V = 1, nu = 0.002))),
  data = h2life,
  nitt = iter,
  burnin = burnin,
  thin = thinning)

save(sire_full, sire_rest, file = "sire_model_comparison.Rda")
```

## Sire Model rstanarm

FIXME

```{r}
library(rstanarm)

fm_full <- stan_lmer(
  NewAge ~ treat - 1 + (1 | sire:treat) + (1 | sire),
  data = h2life,
  prior = normal(0, 2.5),
  prior_intercept = normal(0, 10),
  prior_covariance = decov(regularization = 1,
                           concentration = 1, shape = 1, scale = 1),
  chains = 4,
  cores = 4,
  iter = 2 * 1e4,
  warmup = 2 * 1e3,
  adapt_delta = 0.98)

save(fm_full, file = "rstanarm_mods.Rda")

# loo_full <- loo(fm_full)
# loo_rest <- loo(fm_rest)
# 
# kfold_full <- kfold(fm_full)
# kfold_rest <- kfold(fm_rest)

# save(fm_full, fm_rest, loo_full, loo_rest, kfold_full, kfold_rest,
     # file = "rstanarm_mods.Rda")
```

```{r}
load("rstanarm_mods.Rda")

par(mfrow = 1:2, mar = c(5,3.8,1,0) + 0.1, las = 3)
plot(loo_full, label_points = TRUE)
plot(loo_rest, label_points = TRUE)

compare_models(loo_full, loo_rest)

loo_full
loo_rest
```

```{r}
post <- as.matrix(fm_full) %>% as_data_frame()
colnames(post)

post %>% ggplot(aes(`Sigma[treat:sire:(Intercept),(Intercept)]`)) +
  geom_line(stat = "density")
```
