---
title: "halfsib_survival"
author: "Enoch Ng'oma"
date: "3/7/2017"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Setup

```{r}
library(MCMCglmm)
library(tidyverse)

h2life <- read_delim('../Data/Processed/Female_events_lifespan.txt',
                     delim = "\t") %>% 
  filter(status != 3) %>% 
  mutate(animal = factor(seq(1, nrow(.))),
         treat = as.factor(treat),
         NewAge = as.numeric(scale(NewAge))) %>% 
  dplyr::select(NewAge, sireid, damid, animal, treat) %>% 
  rename(sire = sireid, dam = damid) %>% 
  as.data.frame()

pedigree <- h2life[, c("animal", "sire", "dam")]
pedigree$animal <- as.character(pedigree$animal)
sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()
```

# Sire model MCMCglmm

```{r}
library(parallel)

set.seed(52329487)
iter <- 8000000
burnin <- iter * 0.1
thinning <- 200
chains <- 1

prior <- list(R = list(V = 1, nu = 0.002),
              G = list(G1 = list(V = 1, nu = 0.002),
                       G2 = list(V = 1, nu = 0.002),
                       G3 = list(V = diag(3), nu = 0.002)))

# parameter extension
prior_ext <- list(
  R = list(V = 1, nu = 0.002),
  G = list(G1 = list(V = 1, nu = 0.002, alpha.mu = 0, alpha.V = 1000),
           G2 = list(V = 1, nu = 0.002, alpha.mu = 0, alpha.V = 1000),
           G3 = list(V = diag(3), nu = 0.002,
                     alpha.mu = c(0, 0, 0),
                     alpha.V = diag(3) * 1000)))

system.time({
m6 <- mclapply(1:chains, function(i) {
  MCMCglmm(NewAge ~ treat - 1, 
           random = ~ sire + sire:dam + idh(treat):sire,
           rcov = ~ idh(treat):sire,
           family = "gaussian",
           prior = prior,
           data = h2life,
           nitt = iter,
           burnin = burnin,
           thin = thinning)
}, mc.cores = chains)
})

save(m6, file = "Sire_model.Rda")

# Load model & process ########################################

load("Sire_model.Rda")

m1 <- m6[[1]]

fe <- lapply(m6, function(m) m$Sol)
fe <- do.call(mcmc.list, fe)
plot(fe, ask = FALSE)

re <- lapply(m6, function(m) m$VCV)
re <- do.call(mcmc.list, re)
plot(re, ask = FALSE)

# Fixed
autocorr.diag(fe)
effectiveSize(fe)

# Random
autocorr.diag(re)
effectiveSize(re)

re <- as.mcmc(as.matrix(re))
```

## Sire model comparison

```{r}
iter <- 4000000
burnin <- 50000
thinning <- 200

V_mat <- diag(3)

sire_full_us <- MCMCglmm(
  NewAge ~ treat - 1,
  random = ~ sire + sire:dam + us(treat):sire,
  # rcov = ~ us(treat):sire,
  prior = list(R = list(V = 1, nu = 0.002),
               G = list(G1 = list(V = 1, nu = 0.002),
                        G2 = list(V = 1, nu = 0.002),
                        G3 = list(V = V_mat, nu = 1.002))),
  data = h2life,
  nitt = iter,
  burnin = burnin,
  thin = thinning)
save(sire_full_us, file = "sire_full_us.RDA")

sire_full <- MCMCglmm(
  NewAge ~ treat - 1,
  random = ~ sire + sire:dam + treat:sire,
  # rcov = ~ us(treat):sire,
  prior = list(R = list(V = 1, nu = 0.002),
               G = list(G1 = list(V = 1, nu = 0.002),
                        G2 = list(V = 1, nu = 0.002),
                        G3 = list(V = 1, nu = 0.002))),
  data = h2life,
  nitt = iter,
  burnin = burnin,
  thin = thinning)

sire_rest <- MCMCglmm(
  NewAge ~ treat - 1, 
  random = ~ sire + sire:dam,
  prior = list(R = list(V = 1, nu = 0.002),
               G = list(G1 = list(V = 1, nu = 0.002),
                        G2 = list(V = 1, nu = 0.002))),
  data = h2life,
  nitt = iter,
  burnin = burnin,
  thin = thinning)

save(sire_full, sire_rest, file = "sire_model_comparison.Rda")
```

## Sire Model rstanarm

```{r}
library(rstanarm)
options(mc.cores = parallel::detectCores())

fm_full <- stan_lmer(
  NewAge ~ treat - 1 +
    (1 | sire) + (1 | sire:dam) + (1 | treat:sire),
  data = h2life,
  prior = normal(0, 2.5),
  prior_intercept = normal(0, 10),
  prior_covariance = decov(regularization = 1,
                           concentration = 1, shape = 1, scale = 1),
  chains = 4,
  core = 4,
  iter = 1e4,
  warmup = 1e3)

fm_rest <- stan_lmer(
  NewAge ~ treat - 1 +
    (1 | sire) + (1 | sire:dam),
  data = h2life,
  prior = normal(0, 2.5),
  prior_intercept = normal(0, 10),
  prior_covariance = decov(regularization = 1,
                           concentration = 1, shape = 1, scale = 1),
  chains = 4,
  core = 4,
  iter = 1e4,
  warmup = 1e3)

loo_full <- loo(fm_full)
loo_rest <- loo(fm_rest)

save(fm_full, fm_rest, loo_full, loo_rest, file = "rstanarm_mods.Rda")
```

```{r}
load("rstanarm_mods.Rda")

par(mfrow = 1:2, mar = c(5,3.8,1,0) + 0.1, las = 3)
plot(loo_full, label_points = TRUE)
plot(loo_rest, label_points = TRUE)

compare_models(loo_full, loo_rest)

loo_full
loo_rest
```

```{r}
post <- as.matrix(fm_full) %>% as_data_frame()
colnames(post)

post %>% ggplot(aes(`Sigma[treat:sire:(Intercept),(Intercept)]`)) +
  geom_line(stat = "density")
```

## As trivariate

```{r}
HS <- h2life %>% 
  filter(treat == "HS") %>% rename(Age_HS = NewAge) %>% 
  as.data.frame()
LY <- h2life %>% 
  filter(treat == "LY") %>% rename(Age_LY = NewAge) %>% 
  as.data.frame()
STD <- h2life %>%
  filter(treat == "STD") %>% rename(Age_STD = NewAge) %>% 
  as.data.frame()

h2life_mrg <- full_join(full_join(HS, LY), STD)

prior1 <- list(R = list(V = diag(3) * 1.002, nu = 1.002),
               G = list(G1 = list(V = diag(3) * 1.002, nu = 1.002)))

prior2 <- list(R = list(V = diag(3) / 3, nu = 1.002),
               G = list(G1 = list(V = diag(3) / 3, nu = 1.002)))

prior3 <- list(R = list(V = diag(3) * 1.002, nu = 3),
               G = list(G1 = list(V = diag(3) * 1.002, nu = 3)))

library(parallel)

iter <- 2000000
burnin <- 20000
thinning <- 500
chains <- 12

system.time({
m6 <- mclapply(1:chains, function(i) {
   MCMCglmm(cbind(Age_STD, Age_HS, Age_LY) ~ trait - 1,
         random = ~ us(trait):animal,
         rcov = ~ idh(trait):units,
         data = h2life_mrg,
         prior = prior3,
         pedigree = pedigree,
         family = rep("gaussian", 3),
         nitt = iter,
         burnin = burnin,
         thin = thinning)
}, mc.cores = chains)
})

save(m6, file = "tri_model_p3.Rda")

###############################################################

load("tri_model_p2.Rda")

fe <- lapply(m6, function(m) m$Sol)
fe <- do.call(mcmc.list, fe)
plot(fe, ask = FALSE)
plot(fe[, 1, drop = FALSE], ask = FALSE)
plot(fe[, 2, drop = FALSE], ask = FALSE)
plot(fe[, 3, drop = FALSE], ask = FALSE)

# Extract random effects, convert to mcmc.list
re <- lapply(m6, function(m) m$VCV)
re <- do.call(mcmc.list, re)

plot(re[, 1, drop = FALSE], ask = FALSE)
plot(re[, 2, drop = FALSE], ask = FALSE)
plot(re[, 3, drop = FALSE], ask = FALSE)

autocorr.diag(re)
effectiveSize(re)

# Concatenate samples
re <- as.mcmc(as.matrix(re))

head(re)

# STD vs. HS
plot(re[ , "traitAge_HS:traitAge_STD.animal"])
plot(re[ , "traitAge_STD:traitAge_STD.animal"])
HS_STD <- re[ , "traitAge_HS:traitAge_STD.animal"] /
  sqrt(re[ , "traitAge_STD:traitAge_STD.animal"] *
         re[ , "traitAge_HS:traitAge_HS.animal"])
plot(HS_STD)
posterior.mode(HS_STD)
HPDinterval(HS_STD)

# STD vs. LY
LY_STD <- re[ , "traitAge_LY:traitAge_STD.animal"] /
  sqrt(re[ , "traitAge_STD:traitAge_STD.animal"] *
         re[ , "traitAge_LY:traitAge_LY.animal"])
plot(LY_STD)
posterior.mode(LY_STD)
HPDinterval(LY_STD)

# LY vs. HS
HS_LY <- re[ , "traitAge_HS:traitAge_LY.animal"] /
  sqrt(re[ , "traitAge_LY:traitAge_LY.animal"] *
         re[ , "traitAge_HS:traitAge_HS.animal"])
plot(HS_LY)
posterior.mode(HS_LY)
HPDinterval(HS_LY)
```

```{r}
library(tidyverse)
library(cowplot)

M <- data_frame(`HS vs. STD` = as.numeric(HS_STD),
                `LY vs. STD` = as.numeric(LY_STD),
                `HS vs. LY` = as.numeric(HS_LY))

M %>% gather(key, value) %>%
  ggplot(aes(value, color = key)) +
  geom_line(stat = "density") +
  labs(x = "Genetic Correlation", y = "Density")
```

