---
title: "Dmel half-sib heritability in fecundity"
author: "Kevin Middleton"
date: "3/7/2017"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

#1. "Lifespan fecundity" (sum eggs per vial across days)
#2. Fecundity at weeks 1, 5, 10, e.g.
#3. Model with (week | vial) -- what does that mean?

```{r}
library(knitr)
# purl("h2fec_lifetime_heritability.Rmd", output = "h2fec_lifetime_heritability.R", documentation = 2)
```

```{r}
library(MCMCglmm)
library(tidyverse)
library(cowplot)

source("color_map.R")
source("ggplot_theme.R")
```

#### Heritability ###

```{r}
rerun_MCMC <- FALSE

set.seed(33416)

iter <- 2e7
burnin <- 5e4
thin <- 200
```

## Data for early life fecundity
```{r}
AA <- read.table('../../Data/Processed/eggs_per_female.txt',
                 sep = "\t", header = TRUE,
                 stringsAsFactors = FALSE) %>% 
  select(flipDate, id, fID, treat, age, sireid, damid,
         n_females, eggs_per_female) %>%
  mutate(treat = case_when(
    treat == "HS" ~ "HS",
    treat == "LY" ~ "DR",
    treat == "STD" ~ "C"),
    treat = factor(treat),
    treat = fct_relevel(treat, "C")) %>%
  rename(Diet = treat)

# Prepare data

AA$flipDate <- as.Date(AA$flipDate)

AA <- AA[!is.na(AA$eggs_per_female), ]

# Get early life fec - nearest day 5
Day <- 5
all.ids <- unique(AA$id)

early.fec <- data.frame("id" = character(length=length(all.ids)),
                        "earlyegg"=numeric(length=length(all.ids)),
                        "age"=numeric(length=length(all.ids)),                                           stringsAsFactors = FALSE)

for(ii in 1:length(all.ids))
{
  sub.dat <- subset(AA, id==all.ids[ii])
  early.fec[ii,'id']<-all.ids[ii]
  early.fec[ii,'egg_total']<-sub.dat[which.min(abs(sub.dat$age-Day)),'eggs_per_female']
  early.fec[ii,'age']<-sub.dat[which.min(abs(sub.dat$age-Day)),'age']
  
}

early.fec <-early.fec %>%
  mutate(siredam = str_split(id, "_", simplify = TRUE)[, 1],
         repl = str_split(id, "_", simplify = TRUE)[, 2],
         treat = str_split(id, "_", simplify = TRUE)[, 3],
         sireid = str_split(siredam, "D", simplify = TRUE)[, 1],
         damid = paste0("D", str_split(siredam, "D", simplify = TRUE)[, 2])) %>% 
  select(-siredam)

#RENAME to h2fec and comment below to use

```


## Data for total fecundity
```{r}
h2fec <- read.table("../../Data/Processed/eggs_per_vial.txt",
                    sep = '\t',
                    dec = ".", header = TRUE,
                    stringsAsFactors = FALSE)

source("color_map.R")

# Standardize egg_total
h2fec$egg_total <- as.numeric(scale(h2fec$egg_total))

h2fec$animal <- seq(1, nrow(h2fec))
h2fec$treat <- as.factor(h2fec$treat)
```

##### high sugar, HS

```{r}
HS <- subset(h2fec, treat == "HS")

pedigree <- HS[, c("animal", "sireid", "damid")]
names(pedigree) <- c("animal", "sire", "dam")
pedigree$animal <- as.character(pedigree$animal)
sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()
```

```{r}
# Inverse Gamma(0.001; 0.001)
# a = nu / 2
# b = nu * V / 2

if (rerun_MCMC) {
  t1 <- Sys.time()
  
  prior <- list(R = list(V = 1, nu = 0.002),
                G = list(G1 = list(V = 1, nu = 0.002)))
  
  #model <- mclapply(1:chains, function(i) {
  model <- MCMCglmm(egg_total ~ 1,
                    random = ~ animal,
                    family = "gaussian",
                    prior = prior,
                    pedigree = pedigree,
                    data = HS,
                    nitt = iter,
                    burnin = burnin,
                    thin = thin,
                    verbose = TRUE)
  #}, mc.cores = chains)
  
  save(model, file = "../../Data/Processed/HS_lifetime_FEC.Rda")
  
  t2 <- Sys.time()
  cat(t2-t1)
}

```

```{r HS_analysis}
load("../../Data/Processed/HS_lifetime_FEC.Rda")

# Fixed
plot(model$Sol)
autocorr.diag(model$Sol)
effectiveSize(model$Sol)

# Random
plot(model$VCV)
autocorr.diag(model$VCV)
effectiveSize(model$VCV)

summary(model)

herit.hs <- model$VCV[, "animal"] / (model$VCV[, "animal"] + model$VCV[, "units"])
plot(herit.hs)
median(herit.hs)
h <- HPDinterval(herit.hs)
h1 <- as.data.frame(h)
herit.hs <- as.data.frame(herit.hs)
```

##### Low yeast, LY

```{r}
if (rerun_MCMC) {
  t1<-Sys.time()
  
  LY <- subset(h2fec, treat == "LY")
  
  pedigree <- LY[, c("animal", "sireid", "damid")]
  names(pedigree) <- c("animal", "sire", "dam")
  pedigree$animal <- as.character(pedigree$animal)
  sires <- data.frame(animal = unique(pedigree$sire),
                      sire = NA, dam = NA, stringsAsFactors = FALSE)
  dams <- data.frame(animal = unique(pedigree$dam),
                     sire = NA, dam = NA, stringsAsFactors = FALSE)
  pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()
  
  # Inverse Gamma(0.001; 0.001)
  # a = nu / 2
  # b = nu * V / 2
  
  prior <- list(R = list(V = 1, nu = 0.002),
                G = list(G1 = list(V = 1, nu = 0.002)))
  
  model <- MCMCglmm(egg_total ~ 1,
                    random = ~ animal,
                    family = "gaussian",
                    prior = prior,
                    pedigree = pedigree,
                    data = LY,
                    nitt = iter,
                    burnin = burnin,
                    thin = thin,
                    verbose = TRUE)
  
  save(model, file = "../../Data/Processed/LY_lifetime_FEC.Rda")
  
  t2 <- Sys.time()
  cat(t2 - t1)
}
```

```{r LY_analysis}
load("../../Data/Processed/LY_lifetime_FEC.Rda")

# Fixed
plot(model$Sol)
autocorr.diag(model$Sol)
effectiveSize(model$Sol)

# Random
plot(model$VCV)
autocorr.diag(model$VCV)
effectiveSize(model$VCV)

summary(model)

herit.dr <- model$VCV[, "animal"] / (model$VCV[, "animal"] + model$VCV[, "units"])
plot(herit.dr)
median(herit.dr)
d <- HPDinterval(herit.dr)
d1 <- as.data.frame(d)
herit.dr <- as.data.frame(herit.dr)
```

##### Standard, STD

```{r}
if (rerun_MCMC) {
  s1<-Sys.time()
  
  STD <- subset(h2fec, treat == "STD")
  
  pedigree <- STD[, c("animal", "sireid", "damid")]
  names(pedigree) <- c("animal", "sire", "dam")
  pedigree$animal <- as.character(pedigree$animal)
  sires <- data.frame(animal = unique(pedigree$sire),
                      sire = NA, dam = NA, stringsAsFactors = FALSE)
  dams <- data.frame(animal = unique(pedigree$dam),
                     sire = NA, dam = NA, stringsAsFactors = FALSE)
  pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()
  
  # Inverse Gamma(0.001; 0.001)
  # a = nu / 2
  # b = nu * V / 2
  
  prior <- list(R = list(V = 1, nu = 0.002),
                G = list(G1 = list(V = 1, nu = 0.002)))
  
  model <- MCMCglmm(egg_total ~ 1,
                    random = ~ animal,
                    family = "gaussian",
                    prior = prior,
                    pedigree = pedigree,
                    data = STD,
                    nitt = iter,
                    burnin = burnin,
                    thin = thin,
                    verbose = TRUE)
  
  save(model, file = "../../Data/Processed/STD_lifetime_FEC.Rda")
  
  s2 <- Sys.time()
  cat(s2 - s1)
}
```

```{r STD_analysis}
load("../../Data/Processed/STD_lifetime_FEC.Rda")

# Fixed
plot(model$Sol)
autocorr.diag(model$Sol)
effectiveSize(model$Sol)

# Random
plot(model$VCV)
autocorr.diag(model$VCV)
effectiveSize(model$VCV)

summary(model)

herit.std <- model$VCV[, "animal"] / (model$VCV[, "animal"] + model$VCV[, "units"])
plot(herit.std)
median(herit.std)
c <- HPDinterval(herit.std)
c1 <- as.data.frame(c)
herit.std <- as.data.frame(herit.std)
```

# The three files together

```{r}
herit.hs$Diet <- "HS"
herit.dr$Diet <- "DR"
herit.std$Diet <- "C"

heritab <- rbind(herit.hs, herit.dr, herit.std)
save(heritab, file = "../../Data/Processed/herit_lifetime.Rda")
```

# Plot treatments together

```{r}
load("../../Data/Processed/herit_lifetime.Rda")

Fecundity_h2 <- ggplot(heritab, aes(var1, fill = Diet)) + 
  geom_density(alpha = 0.2) +
  expand_limits(x = c(0, 1.0)) +
  xlab("Heritability") +
  ylab("Density") +
  theme(legend.position=c(0.85, 0.85)) +
  my_theme +
  tx_fill_map()
Fecundity_h2
ggsave(Fecundity_h2, file = "../../Figures/Fecundity_heritability_lifetime_plots.pdf",
       width = 4, height = 4)
save(Fecundity_h2, file = "../../Figures/Fecundity_h2.Rda")
```
