---
title: "Fecundity MANOVA"
author: "Kevin Middleton"
date: "3/7/2017"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r}
library(knitr)
# purl("h2fec_lifetime_MANOVA.Rmd", output = "h2fec_lifetime_MANOVA.R", documentation = 2)
```

# Setup

```{r setup}
rerun <- FALSE

set.seed(224819)

library(MCMCglmm)
library(tidyverse)
library(parallel)
```

```{r}
h2fec <- read.table("../../Data/Processed/eggs_per_vial.txt",
                    sep = '\t',
                    dec = ".", header = TRUE,
                    stringsAsFactors = FALSE)

# Standardize egg_total
h2fec$egg_total <- as.numeric(scale(h2fec$egg_total))

h2fec$animal <- seq(1, nrow(h2fec))
h2fec$treat <- as.factor(h2fec$treat)

pedigree <- h2fec[, c("animal", "sireid", "damid")]
names(pedigree) <- c("animal", "sire", "dam")
pedigree$animal <- as.character(pedigree$animal)
pedigree$sire <- as.character(pedigree$sire)
pedigree$dam <- as.character(pedigree$dam)
sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>%
  as.data.frame()

genet_corr <- tibble(model = character(),
                     HS_STD = numeric(),
                     LY_STD = numeric(),
                     HS_LY = numeric(),
                     n_eff = numeric())

iter <- 6.5e6
burnin <- 5e4
thinning <- 500
chains <- 12
```

## MANOVA analysis

```{r MANOVA_Models, cache=TRUE}
# 19 hours run time on nivalis (6e5 would be reasonable!)
if (rerun) {
  HS <- h2fec %>% 
    filter(treat == "HS") %>% rename(Eggs_HS = egg_total) %>% 
    as.data.frame()
  LY <- h2fec %>% 
    filter(treat == "LY") %>% rename(Eggs_LY = egg_total) %>% 
    as.data.frame()
  STD <- h2fec %>%
    filter(treat == "STD") %>% rename(Eggs_STD = egg_total) %>% 
    as.data.frame()
  
  h2fec_mrg <- full_join(full_join(HS, LY), STD)
  
  prior1 <- list(R = list(V = diag(3) * 1.002, nu = 1.002),
                 G = list(G1 = list(V = diag(3) * 1.002, nu = 0.002)))
  
  priors <- list(prior1)
  prior_names <- c("Tri: V = diag(3) * 1.002, nu = 0.02")
  
  for (ii in 1:length(priors)) {
    prior <- priors[[ii]]
    fm <- mclapply(1:chains, function(i) {
      MCMCglmm(cbind(Eggs_STD, Eggs_HS, Eggs_LY) ~ trait - 1,
               random = ~ us(trait):animal,
               rcov = ~ idh(trait):units,
               data = h2fec_mrg,
               prior = prior,
               pedigree = pedigree,
               family = rep("gaussian", 3),
               nitt = iter,
               burnin = burnin,
               thin = thinning)
    }, mc.cores = chains)
    outfile <- paste0("../../Data/Processed/FEC_lifetime_model_prior", ii, ".Rda")
    save(fm, file = outfile)
    
    re <- lapply(fm, function(m) m$VCV)
    re <- do.call(mcmc.list, re)
    re <- as.mcmc(as.matrix(re))
    
    n_eff <- effectiveSize(re)
    
    # STD vs. HS
    HS_STD <- re[ , "traitEggs_HS:traitEggs_STD.animal"] /
      sqrt(re[ , "traitEggs_STD:traitEggs_STD.animal"] *
             re[ , "traitEggs_HS:traitEggs_HS.animal"])
    
    # STD vs. LY
    LY_STD <- re[ , "traitEggs_LY:traitEggs_STD.animal"] /
      sqrt(re[ , "traitEggs_STD:traitEggs_STD.animal"] *
             re[ , "traitEggs_LY:traitEggs_LY.animal"])
    
    # LY vs. HS
    HS_LY <- re[ , "traitEggs_HS:traitEggs_LY.animal"] /
      sqrt(re[ , "traitEggs_LY:traitEggs_LY.animal"] *
             re[ , "traitEggs_HS:traitEggs_HS.animal"])
    
    genet_corr <- bind_rows(genet_corr,
                            tibble(model = prior_names[[ii]],
                                   HS_STD = median(HS_STD),
                                   LY_STD = median(LY_STD),
                                   HS_LY = median(HS_LY),
                                   n_eff = mean(n_eff)))
  }
  
  write_csv(genet_corr, path = "../../Data/Processed/Genetic_Correlations_Fecundity.csv")
}
```

### Analyze model

```{r MANOVA_Analysis}
load("../../Data/Processed/FEC_lifetime_model_prior1.Rda")

fe <- lapply(fm, function(m) m$Sol)
fe <- do.call(mcmc.list, fe)
plot(fe, ask = FALSE)
plot(fe[, 1, drop = FALSE], ask = FALSE)
plot(fe[, 2, drop = FALSE], ask = FALSE)
plot(fe[, 3, drop = FALSE], ask = FALSE)

# Extract random effects, convert to mcmc.list
re <- lapply(fm, function(m) m$VCV)
re <- do.call(mcmc.list, re)

plot(re[, 1, drop = FALSE], ask = FALSE)
plot(re[, 2, drop = FALSE], ask = FALSE)
plot(re[, 3, drop = FALSE], ask = FALSE)

autocorr.diag(re)
effectiveSize(re)

# Concatenate samples
re <- as.mcmc(as.matrix(re))

head(re)

# STD vs. HS
plot(re[ , "traitEggs_HS:traitEggs_STD.animal"])
plot(re[ , "traitEggs_STD:traitEggs_STD.animal"])
HS_STD <- re[ , "traitEggs_HS:traitEggs_STD.animal"] /
  sqrt(re[ , "traitEggs_STD:traitEggs_STD.animal"] *
         re[ , "traitEggs_HS:traitEggs_HS.animal"])
plot(HS_STD)
median(HS_STD)
HPDinterval(HS_STD)

# STD vs. LY
LY_STD <- re[ , "traitEggs_LY:traitEggs_STD.animal"] /
  sqrt(re[ , "traitEggs_STD:traitEggs_STD.animal"] *
         re[ , "traitEggs_LY:traitEggs_LY.animal"])
plot(LY_STD)
median(LY_STD)
HPDinterval(LY_STD)

# LY vs. HS
HS_LY <- re[ , "traitEggs_HS:traitEggs_LY.animal"] /
  sqrt(re[ , "traitEggs_LY:traitEggs_LY.animal"] *
         re[ , "traitEggs_HS:traitEggs_HS.animal"])
plot(HS_LY)
median(HS_LY)
HPDinterval(HS_LY)
```

### Plot for poster

```{r}
library(tidyverse)
library(cowplot)

B <- data_frame(`HS vs. STD` = as.numeric(HS_STD),
                `LY vs. STD` = as.numeric(LY_STD),
                `HS vs. LY` = as.numeric(HS_LY))

colMeans(B)

B %>% gather(Comparison, value) %>%
  ggplot(aes(value, color = Comparison)) +
  geom_line(stat = "density", size = 2) +
  labs(x = "Genetic Correlation", y = "Density") +
  theme(legend.position = c(0.15, 0.85),
        text = element_text(size = 24),
        legend.text = element_text(size = 18))
ggsave(last_plot(), file = "Genetic_Correlation_Plot.pdf",
       width = 8, height = 6)
```

## Model following Ingleby et al. 2013

# Setup data as above

```{r}
V_nu_to_a_b <- function(V, nu) {
  require(tidyverse)
  require(invgamma)
  
  a <- nu / 2
  b <- (nu * V) / 2
  
  p <- tibble(
    x = seq(0, 10, length = 200),
    y = dinvgamma(x, a, b)) %>% 
    ggplot(aes(x, y)) +
    geom_line()
  print(p)
  
  return(list(alpha = a, beta = b))
}
```

```{r Sire_Models, cache=TRUE}
V_nu_to_a_b(1, 0.002)

if (rerun) {
  
  prior1 <- list(R = list(V = 1, nu = 0.002),
                 G = list(G1 = list(V = diag(3) / 3, nu = 0.002)))
  
  prior2 <- list(R = list(V = 1, nu = 0.002),
                 G = list(G1 = list(V = diag(3) * 0.5 * 0.7, nu = 0.002)))
  
  M <- matrix(0.5 * 0.7, 3, 3)
  diag(M) <- 0.5
  prior3 <- list(R = list(V = 1, nu = 0.002),
                 G = list(G1 = list(V = M, nu = 0.002)))
  
  priors <- list(prior1, prior2, prior3)
  prior_names <- c("Sire: V = diag(3) / 3, nu = 0.002",
                   "Sire: V = diag(3) * 0.5 * 0.7, nu = 0.002",
                   "Sire: V = 0.5 diag, 0.35 off-diag, nu = 0.002")
  
  h2fec$egg_total_std <- scale(h2fec$egg_total)
  
  for (ii in 1:length(priors)) {
    prior <- priors[[ii]]
    
    fm <- mclapply(1:chains, function(i) {
      MCMCglmm(egg_total_std ~ treat,
               random = ~ us(treat):sireid,
               data = h2fec,
               prior = prior,
               family = "gaussian",
               nitt = iter,
               burnin = burnin,
               thin = thinning,
               verbose = TRUE)
    }, mc.cores = chains)
    
    outfile <- paste0("../../Data/Processed/sire_model_prior", ii, ".Rda")
    save(fm, file = outfile)
    
    re <- lapply(fm, function(m) m$VCV)
    re <- do.call(mcmc.list, re)
    re <- as.mcmc(as.matrix(re))
    n_eff <- effectiveSize(re)
    
    # STD vs. HS
    HS_STD <- re[ , "treatHS:treatSTD.sireid"] /
      sqrt(re[ , "treatHS:treatHS.sireid"] *
             re[ , "treatSTD:treatSTD.sireid"])
    median(HS_STD)
    
    # STD vs. LY
    LY_STD <- re[ , "treatSTD:treatLY.sireid"] /
      sqrt(re[ , "treatSTD:treatSTD.sireid"] *
             re[ , "treatLY:treatLY.sireid"])
    median(LY_STD)
    
    # LY vs. HS
    HS_LY <- re[ , "treatHS:treatLY.sireid"] /
      sqrt(re[ , "treatLY:treatLY.sireid"] *
             re[ , "treatHS:treatHS.sireid"])
    median(HS_LY)
    
    genet_corr <- bind_rows(genet_corr,
                            tibble(model = prior_names[[ii]],
                                   HS_STD = median(HS_STD),
                                   LY_STD = median(LY_STD),
                                   HS_LY = median(HS_LY),
                                   n_eff = mean(n_eff)))
    
  }
  write_csv(genet_corr, path = "Genetic_Correlations.csv")
  
  kable(genet_corr, digits = 3)
}

```

### Analyze model

```{r Sire_Analysis}
load("../../Data/Processed/sire_model_prior1.Rda")

fe <- lapply(fm, function(m) m$Sol)
fe <- do.call(mcmc.list, fe)
plot(fe, ask = FALSE)

# Extract random effects, convert to mcmc.list
re <- lapply(fm, function(m) m$VCV)
re <- do.call(mcmc.list, re)

plot(re[, 1:3], ask = FALSE)
plot(re[, 4:6], ask = FALSE)
plot(re[, 7:9], ask = FALSE)
plot(re[, 10], ask = FALSE)

effectiveSize(re)

# Concatenate samples
re <- as.mcmc(as.matrix(re))
colnames(re)

# ??? Heritability ????
HS <- re[, "treatHS:treatHS.sireid"] / (re[, "treatHS:treatHS.sireid"] + re[, "units"])
median(HS)

LY <- re[, "treatLY:treatLY.sireid"] / (re[, "treatLY:treatLY.sireid"] + re[, "units"])
median(LY)

STD <- re[, "treatSTD:treatSTD.sireid"] / (re[, "treatSTD:treatSTD.sireid"] + re[, "units"])
median(STD)

# STD vs. HS
HS_STD <- re[ , "treatHS:treatSTD.sireid"] /
  sqrt(re[ , "treatHS:treatHS.sireid"] *
         re[ , "treatSTD:treatSTD.sireid"])
plot(HS_STD)
median(HS_STD)
HPDinterval(HS_STD)

# STD vs. LY
LY_STD <- re[ , "treatSTD:treatLY.sireid"] /
  sqrt(re[ , "treatSTD:treatSTD.sireid"] *
         re[ , "treatLY:treatLY.sireid"])
plot(LY_STD)
median(LY_STD)
HPDinterval(LY_STD)

# LY vs. HS
HS_LY <- re[ , "treatHS:treatLY.sireid"] /
  sqrt(re[ , "treatLY:treatLY.sireid"] *
         re[ , "treatHS:treatHS.sireid"])
plot(HS_LY)
median(HS_LY)
HPDinterval(HS_LY)
```
