---
title: "Dmel half-sib heritability in fecundity"
author: "Kevin Middleton"
date: "3/7/2017"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

1. "Lifespan fecundity" (sum eggs per vial across days)
2. Fecundity at weeks 1, 5, 10, e.g.
3. Model with (week | vial) -- what does that mean?


```{r}
library(MCMCglmm)
library(tidyverse)
library(cowplot)
```

#### Heritability ###

```{r eval=TRUE}
set.seed(33416)

iter <- 200000 #2e6
burnin <- 20000 #2e4

rerun <- TRUE
```

## Per female

```{r}
h2fec <- read.table('../../Data/Processed/eggs_per_female.txt',
                     sep = "\t", dec = ".", header = TRUE,
                     stringsAsFactors = FALSE)
#h2_filtered <- h2fec[h2fec$eggs_per_female, ]
h2fec$animal <- seq(1, nrow(h2fec))
h2fec$treat <- as.factor(h2fec$treat)
```

##### high sugar, HS

```{r}
HS <- subset(h2fec, treat == "HS")

pedigree <- HS[, c("animal", "sireid", "damid")]
names(pedigree) <- c("animal", "sire", "dam")
pedigree$animal <- as.character(pedigree$animal)
sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()
```

```{r}
# Inverse Gamma(0.001; 0.001)
# a = nu / 2
# b = nu * V / 2

t1<-Sys.time()

prior <- list(R = list(V = 1, nu = 0.002),
              G = list(G1 = list(V = 1, nu = 0.002)))

#model <- mclapply(1:chains, function(i) {
model <- MCMCglmm(eggs_per_female ~ 1,
                  random = ~ animal,
                  family = "gaussian",
                  prior = prior,
                  pedigree = pedigree,
                  data = HS,
                  nitt = iter,
                  burnin = burnin,
                  thin = 50,
                  verbose = FALSE)
#}, mc.cores = chains)

save(model, file = "../../Data/Processed/HS_FEC.Rda")

t2<-Sys.time()
cat(t2-t1)

```

```{r}
load("../../Data/Processed/HS_FEC.Rda")
# Fixed
plot(model$Sol)
autocorr.diag(model$Sol)
effectiveSize(model$Sol)

# Random
plot(model$VCV)
autocorr.diag(model$VCV)
effectiveSize(model$VCV)

summary(model)

herit <- model$VCV[, "animal"] / (model$VCV[, "animal"] + model$VCV[, "units"])
plot(herit)
median(herit)
f <- HPDinterval(herit)
k <- as.data.frame(f)
```

# plot hs with ggplot

```{r}
density(herit)

hs.samp<-data.frame(('h2'=herit)) # HPDinterval(as.mcmc(herit)))

ggplot(hs.samp, aes(x=var1), y=k) +
  geom_histogram()+
  geom_vline(xintercept = median(herit))

rm(model) 
```

##### Low yeast, LY

```{r}
t1<-Sys.time()

LY <- subset(h2_filtered, treat == "LY")

pedigree <- LY[, c("animal", "sireid", "damid")]
names(pedigree) <- c("animal", "sire", "dam")
pedigree$animal <- as.character(pedigree$animal)
sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()

# Inverse Gamma(0.001; 0.001)
# a = nu / 2
# b = nu * V / 2

prior <- list(R = list(V = 1, nu = 0.002),
              G = list(G1 = list(V = 1, nu = 0.002)))

model <- MCMCglmm(eggs_per_female ~ 1,
                  random = ~ animal,
                  family = "gaussian",
                  prior = prior,
                  pedigree = pedigree,
                  data = LY,
                  nitt = iter,
                  burnin = burnin,
                  thin = 50,
                  verbose = FALSE)

save(model, file = "../../Data/Processed/LY_FEC.Rda")

t2<-Sys.time()
cat(t2-t1)
```

```{r}
load("../../Data/Processed/LY_FEC.Rda")
# Fixed
plot(model$Sol)
autocorr.diag(model$Sol)
effectiveSize(model$Sol)

# Random
plot(model$VCV)
autocorr.diag(model$VCV)
effectiveSize(model$VCV)

summary(model)

herit.dr <- model$VCV[, "animal"] / (model$VCV[, "animal"] + model$VCV[, "units"])
plot(herit.dr)
median(herit.dr)
HPDinterval(herit.dr)
```

# plot LY with ggplot

```{r}
density(herit.dr)

dr.samp<-data.frame(('h2'=herit.dr)) # HPDinterval(as.mcmc(dr.herit)))

ggplot(dr.samp, aes(x=var1), y=k) +
  geom_histogram()+
  geom_vline(xintercept = median(herit.dr))

rm(model)
```

##### Standard, STD

```{r}
s1<-Sys.time()

STD <- subset(h2_filtered, treat == "STD")

pedigree <- STD[, c("animal", "sireid", "damid")]
names(pedigree) <- c("animal", "sire", "dam")
pedigree$animal <- as.character(pedigree$animal)
sires <- data.frame(animal = unique(pedigree$sire),
                    sire = NA, dam = NA, stringsAsFactors = FALSE)
dams <- data.frame(animal = unique(pedigree$dam),
                   sire = NA, dam = NA, stringsAsFactors = FALSE)
pedigree <- bind_rows(sires, dams, pedigree) %>% as.data.frame()

# Inverse Gamma(0.001; 0.001)
# a = nu / 2
# b = nu * V / 2

prior <- list(R = list(V = 1, nu = 0.002),
              G = list(G1 = list(V = 1, nu = 0.002)))

model <- MCMCglmm(eggs_per_female ~ 1,
                  random = ~ animal,
                  family = "gaussian",
                  prior = prior,
                  pedigree = pedigree,
                  data = STD,
                  nitt = iter,
                  burnin = burnin,
                  thin = 50,
                  verbose = FALSE)

save(model, file = "../../Data/Processed/STD_FEC.Rda")

s2<-Sys.time()
cat(s2-s1)
```

```{r}
load("../../Data/Processed/STD_FEC.Rda")
# Fixed
plot(model$Sol)
autocorr.diag(model$Sol)
effectiveSize(model$Sol)

# Random
plot(model$VCV)
autocorr.diag(model$VCV)
effectiveSize(model$VCV)

summary(model)

herit.c <- model$VCV[, "animal"] / (model$VCV[, "animal"] + model$VCV[, "units"])
plot(herit.c)
median(herit.c)
p <- HPDinterval(herit.c)
q <- as.data.frame(f)
```

# Plot STD with ggplot

```{r}
density(herit.c)

c.samp<-data.frame(('h2'=herit.c)) # HPDinterval(as.mcmc(dr.herit)))

ggplot(c.samp, aes(x=var1), y=k) +
  geom_histogram()+
  geom_vline(xintercept = median(herit.c))
```

# The three files together

```{r, }
hs.samp$Diet <- "HS"
dr.samp$Diet <- "DR"
c.samp$Diet <- "C"

hs.samp$HS <- NULL
dr.samp$DR <- NULL
c.samp$C <- NULL
heritab <- rbind(hs.samp, dr.samp, c.samp)
save(heritab, file = "../../Data/Processed/herit.Rda")
```

# Plot treatments together

```{r, dens}
ll<- 7.4
ss<-0.2

#pdf("../../Data/Figures/heritability_plots.pdf",width=6,height=4)
par(mar=c(4.5,4.5,0.5,0.5))
 ggplot(heritab, aes(var1, fill = Diet)) + 
  geom_density(alpha = 0.2) +
  geom_segment(x = 0.2479849, y = ll+ss, xend = 0.4984068, yend = ll+ss, position = "identity", colour = "mediumpurple1")+
  geom_segment(x = 0.2071338, y = ll+ss+ss, xend = 0.4288147, yend = ll+ss+ss, position = "identity", colour = "darkseagreen2")+
  geom_segment(x = 0.3350174, y = ll, xend = 0.6070656, yend = ll, position = "identity", colour = "lightpink")+
  #coord_cartesian(xlim=c(0, 1), ylim=c(0, 1)) + #adjust frame of x-axis
  #scale_x_continuous(expand=c(0, 0), limits=c(-3, 100)) + #limit plot area on x-axix
  expand_limits(y=c(0,8)) + expand_limits(x=c(0,0.8)) +
  theme(axis.title = element_text(size=16)) +
  xlab("Heritability") + ylab("Density") +
  theme(legend.position=c(0.85, 0.85)) +
  scale_fill_discrete(name="Diet", labels=c("C", "DR", "HS")) 
#dev.off()
```

# extract .R for the shell

```{r}
#library(knitr)
#purl("h2fec_heritability.Rmd", output = "h2fec_heritability.R", documentation = 2)
```



