---
title: "halfsib_survival - kaplan-meier"
author: "Enoch Ng'oma"
date: "3/7/2017"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Analysis of lifespan 
# Half-sibling fly data

# data
```{r}

h2life <- read.table('../../Data/Processed/Female_events_lifespan.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE)
```
# packages
```{r}

library(survival)
library(survminer)
library(splines) #needed by survival package
library(tidyverse) 
library(forcats)
library(cowplot)
```

##### density (ggplot)
```{r, dens}
pdf("../../Figures/density_all-data_ggpl.pdf",width=6,height=4)
par(mar=c(4.5,4.5,0.5,0.5))
 ggplot(h2life, aes(NewAge, fill = treat)) + 
  geom_density(alpha = 0.2) +
  coord_cartesian(xlim=c(-5, 101), ylim=c(0, 0.04)) + #adjust frame of x-axis
  scale_x_continuous(expand=c(0, 0), limits=c(-3, 100)) + #limit plot area on x-axix
  scale_color_manual(values=c("#CC6666", "#9999CC", "#66CC99")) +
  theme(axis.title = element_text(face="bold", size=16)) +
  xlab("Age(days)") + ylab("Density") +
  theme(legend.position=c(0.1, 0.9)) +
  scale_fill_discrete(name="Diet", labels=c("HS", "DR", "C")) 
dev.off()
```

# Kaplan-Meier plot by diet 
# columns: RIL, NewAge, status

```{r treat}

# by treatment groups
h2.treat <- survfit(Surv(NewAge, status==2) ~ treat, conf.type="log", 
                    conf.int=0.95, type="kaplan-meier", error="greenwood",
                    data=h2life)
# h2.treat
summary(h2.treat)$table

pdf("../../Figures/K-M_treatments_summarized.pdf",width=6,height=4)
par(mar=c(4.5,4.5,0.5,0.5))
plot(h2.treat, conf.int = F, mark.time=FALSE, #masks censored events
     xlab="Age (days)", ylab="Proportion alive",
     col=c("#DD9999", "#66CC99", "#9999CC"), lwd=3,
     cex.axis=1, cex.lab=1)
#mtext("KM survival curve for RILs")
abline(0.1,0, lty=3, lwd=1)
abline(0.5,0, lty=3, lwd=1)
legend(80,1, c("HS", "DR", "C"), lwd=3, text.font=1, bty = "n", y.intersp = 1.0, 
       col=c("#DD9999", "#66CC99", "#9999CC"))
dev.off()
```

# cummulative hazard
```{r}

pdf("../../Figures/CumHaz_treatment_summary.pdf",width=6,height=4)
par(mar=c(4.5,4.5,0.5,0.5))
plot(h2.treat, fun="cumhaz", lty=1,conf.int=F, mark.time=FALSE,
     xlab="Age (days)", ylab="Proportion alive", 
     col=c("#DD9999", "#66CC99", "#9999CC"), lwd=3,
     cex.axis=1, cex.lab=1)
legend(0,7.7, c("HS", "DR", "C"),lty=1, lwd=3,text.font=1, bty = "n",
       col=c("#DD9999", "#66CC99", "#9999CC"))
dev.off()
```

# test differences
```{r testdiff}

test_all <- survdiff(Surv(NewAge, status==2) ~ treat, data=h2life, rho=0) #log-rank (Mantel-Haenszel) test
test_all1 <- survdiff(Surv(NewAge, status==2) ~ treat, data=h2life, rho=1) # Wilcoxon (Peto & Peto test)

test_all
test_all1
```

# pairwise tests
```{r}
test_pairwise <- pairwise_survdiff(Surv(NewAge, status==2) ~ treat, 
                                   data=h2life, p.adjust.method = "bonferroni", rho=0)
test_pairwise1 <- pairwise_survdiff(Surv(NewAge, status==2) ~ treat, 
                                    data=h2life, p.adjust.method = "bonferroni", rho=1)

test_pairwise
test_pairwise1

# significance symbols
symnum(test_pairwise$p.value, cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
   symbols = c("****", "***", "**", "*", "+", " "),
   abbr.colnames = FALSE, na = "")

symnum(test_pairwise1$p.value, cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
   symbols = c("****", "***", "**", "*", "+", " "),
   abbr.colnames = FALSE, na = "")
```

#reaction norms for sire families

```{r}
# remove censored events
h2rn_filtered <- h2life[h2life$status!=3, ] 

# prep each treatment into its own column

#pull HS and compute median
HS <- subset(h2rn_filtered, treat == "HS")
hs_trim <- cbind.data.frame(HS$sireid, HS$NewAge)
hs_med <- aggregate(. ~ HS$sireid, data=hs_trim, FUN=median)
hs_med[,2] <- NULL
colnames(hs_med) <- c("sireid","age")
hs_med$diet<-"HS"

#pull LY and compute median
DR <- subset(h2rn_filtered, treat == "LY")
dr_trim <- cbind.data.frame(DR$sireid, DR$NewAge)
dr_med <- aggregate(. ~ DR$sireid, data=dr_trim, FUN=median)
dr_med[,2] <- NULL
colnames(dr_med) <- c("sireid","age")
dr_med$diet<-"DR"

#pull STD and compute median
C <- subset(h2rn_filtered, treat == "STD")
c_trim <- cbind.data.frame(C$sireid, C$NewAge)
c_med <- aggregate(. ~ C$sireid, data=c_trim, FUN=median)
c_med[,2] <- NULL
colnames(c_med) <- c("sireid","age")
c_med$diet<-"C"

#join data frames
mlife1 <- rbind(hs_med, c_med, dr_med)
mlife1<-mlife1[!(mlife1$sireid=="S39"),]
#attach a column of diet to each data frame before joining; use that as fill

#reorder x-axis (ggplot default is alphabetical)
mlife1$diet <- as.character(mlife1$diet) #turn diet col into a char vector
mlife1$diet <- factor(mlife1$diet, levels=unique(mlife1$diet)) #back to ordered factor
#save(mlife1, file = "/Users/ngomae/Documents/H2_Analysis/h2lifespan/Evo17_Portland/h2reacts.Rda")

#plot reaction norms for sire families
pdf("../../Figures/h2life_reaction_norms.pdf",width=6,height=4)
par(mar=c(4.5,4.5,0.5,0.5))
ggplot(mlife1, aes(x = mlife1$diet, y = mlife1$age)) +
  geom_point(size = 2)+
  geom_line(aes(group = paste(sireid), alpha = 0.2)) +
  xlab("Dietary condition") + ylab("Median lifespan (days)") +
  theme(legend.position="none") +
  scale_fill_discrete(name="Diet", labels=c("HS", "DR", "C")) 
dev.off()
```

# lifespan-fecundity correlation

```{r}
# read in fecundity data
h2fec_phenotype <- read.table('../../Data/Processed/eggs_per_vial.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE)

h2fec_phenotype <- as_tibble(h2fec_phenotype)
h2fec_phenotype <- dplyr::rename(h2fec_phenotype, Diet = treat)

# change LY to DR, STD to C

h2fec_phenotype %>%
     mutate(Diet=replace(Diet, Diet=="LY", "DR")) %>%
     mutate(Diet=replace(Diet, Diet=="STD", "C"))
```     

```{r}
font_size <- 10
my_theme <- theme(
  axis.text = element_text(size = font_size),
  axis.title = element_text(size = font_size),
  legend.text = element_text(size = font_size),
  legend.title=element_text(size = font_size),
  plot.title = element_text(size = font_size + 1))


newdata<-h2life[,c('id','NewAge','treat','repl','status')]
```

```{r}
# rename treat as Diet
newdata <- rename(newdata, Diet = treat)

# change LY to DR, STD to C
newdata <- newdata %>%
     mutate(Diet=replace(Diet, Diet=="LY", "DR")) %>%
     mutate(Diet=replace(Diet, Diet=="STD", "C"))
```


```{r}
km.treat <- survfit(Surv(NewAge, status==2) ~ id, conf.type="log", 
                    conf.int=0.95, type="kaplan-meier", error="greenwood",
                    data=newdata)
med.dat<-summary(km.treat)$table[,'median']

ids<-strsplit(names(med.dat), split="=", fixed=TRUE)
ids<-unlist(lapply(ids, function(x) x[2]))
ids<-strsplit(ids, split=".",fixed=TRUE)

ll.dat<-data.frame('id'=unlist(lapply(ids, function(x) x[1])),
                   'Diet'=unlist(lapply(ids, function(x) x[2])),
                   'repl'=unlist(lapply(ids, function(x) x[3])),
                   'Median'=med.dat,stringsAsFactors=FALSE)

ll.dat.mean <- ll.dat %>%
  group_by(id, Diet) %>% 
  select(-repl) %>% 
  summarize("mean") %>% 
  rename("Mean_of_Median" = Median)  

# to discard the row names column, write to file
ll.dat <- select(ll.dat.mean, id,Mean_of_Median)
write.table(ll.dat, "../../Data/Processed/h2_median_lifespan.txt", row.names=FALSE, sep="\t")

ll.dat<-read.table("../../Data/Processed/h2_median_lifespan.txt",
                   sep="\t",header=TRUE,stringsAsFactors=FALSE) 
```

```{r}
# merge h2fec_phenotype and newdata
comb_phenotype <- merge(h2fec_phenotype,ll.dat,by="id") %>%
  select(id, Diet, Mean_of_Median, egg_total)
```


```{r}
#ggplot(comb_phenotype,aes(x = Diet, y = Median, group = Treatment, fill=Treatment))  

mf <- ggplot(comb_phenotype, aes(Mean_of_Median, egg_total, color=Diet))
mf + geom_point() + labs(x = "Mean_of_Median (days)", y = "Total eggs") 
```


```{r}
ll.dat.merge <- merge(ll.dat, ll.dat.mean) %>%
  arrange(Diet, Mean_of_Median) %>% 
  mutate(id = fct_inorder(id))

rr<-cbind(levels(ll.dat.merge$RIL), rep(1:2, times=40))
colnames(rr)<-c('RIL','RILcol')

ll.dat.merge<-merge(ll.dat.merge, rr,sort=FALSE)


p1<-
  #subset(RIL %in% unique(RIL)[1:15]) %>% 
  ggplot(ll.dat.merge,aes(x = RIL, y = Median, group = Treatment, fill=Treatment))  +
  #geom_point(position = position_dodge(width = 0.5),alpha=0.3, size=2) +
  theme(axis.text.x = element_blank(), legend.position = 'none') +
  stat_summary(fun.y = mean,
               position = position_dodge(width = 0.9),
               geom = "bar", alpha=1/2) +
  geom_point(aes(color=Treatment), position = position_dodge(width = 0.9),size=0.75) +
  scale_color_manual(values = c("tan", "darkolivegreen1"))+
  ylab("Median Lifespan")
#  stat_summary(fun.data = mean_se, 
#              geom = "errorbar", 
#             position = position_dodge(width = 0.9)) 
save(p1,file="Plots/Figure3a.pdf")
#ggsave(file="Plots/Lifespan_pheno.pdf",width=8, height=4)
```



