---
title: "Two_trait"
author: "EGK"
date: "5/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(forcats)
library(survival)


```

## Load Data

```{r}

h2fec_phenotype <- read.table('../../Data/Processed/eggs_per_vial.txt',
                              sep = "\t", header = TRUE,
                              stringsAsFactors = FALSE) %>% 
  rename(Diet = treat) %>% 
  mutate(Diet = case_when(
    Diet == "HS" ~ "HS",
    Diet == "LY" ~ "DR",
    Diet == "STD" ~ "C"),
    Diet = factor(Diet),
    Diet = fct_relevel(Diet, "C"))


h2life <- read.table('../../Data/Processed/Female_events_lifespan.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE) %>% 
  mutate(treat = case_when(
    treat == "HS" ~ "HS",
    treat == "LY" ~ "DR",
    treat == "STD" ~ "C"),
    treat = factor(treat),
    treat = fct_relevel(treat, "C"))


```

## Summarize 

```{r}

km_sire <- survfit(Surv(NewAge, status==2) ~ id, conf.type="log", 
                    conf.int=0.95, type="kaplan-meier", error="greenwood",
                    data=h2life)
med.dat<-summary(km_sire)$table[,'median']

ids<-strsplit(names(med.dat), split="=", fixed=TRUE)
ids<-unlist(lapply(ids, function(x) x[2]))
ids_t <- ids
ids<-strsplit(ids, split="_",fixed=TRUE)

med.life<-data.frame('id'=ids_t,
                     'Family'=unlist(lapply(ids, function(x) x[1])),
                   'Replicate'=unlist(lapply(ids, function(x) x[2])),
                   'Treatment'=unlist(lapply(ids, function(x) x[3])),
                   'Median'=med.dat,stringsAsFactors=FALSE)


all.dat <- merge(med.life, )


```
