---
title: "h2 fecundity analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cowplot)
library(readxl)
library(ggrepel)
```

## Load and merge data

```{r}
M <- suppressWarnings(
  read_excel("../../Data/Processed/feclife_with-image-ids.xlsx")
)
areas <- read_csv("../../Data/Processed/area_summation_h2_fec_images.csv",
                  col_types = "cii") %>% 
  select(-lower_thresh)
M <- left_join(M, areas)
```

## Regression on handcounted images

```{r}
optimized_threshold <- 46

actual <- suppressWarnings(
  read_excel("../../Data/Processed/hd_hand_counted.xlsx") %>% 
  dplyr::select(camera_id, handcount)
)

bad_images <- read_excel("../../Data/Processed/bad_images.xlsx") %>% 
  filter(status == "bad") %>% 
  rename(camera_id = cameraid)

# Drop bad images
actual <- actual %>%
  filter(!(camera_id %in% bad_images$camera_id))

actual_area <- read_csv("../../Data/Processed/area_summation_fine.csv") %>% 
  filter(lower_thresh == optimized_threshold)

actual <- full_join(actual, actual_area)

ggplot(actual, aes(x = area, y = handcount)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

Check these areas: should be in the test_case batch but aren't.

```{r}
actual %>% 
  filter(is.na(area))
```

## Examine possibly bad images

```{r check_bad_images}
plot_jpeg = function(path, add=FALSE) {
  # https://stackoverflow.com/a/28729601/168137
  require('jpeg')
  jpg = readJPEG(path, native=T) # read the file
  res = dim(jpg)[2:1] # get the resolution, [x, y]
  if (!add) # initialize an empty plot area if add==FALSE
    plot(1, 1,
         xlim=c(1,res[1]),ylim=c(1,res[2]),
         asp=1, type = 'n', xaxs = 'i', yaxs = 'i', xaxt = 'n', yaxt = 'n',
         xlab = '', ylab = '', bty = 'n', main = path)
  rasterImage(jpg, 1, 1, res[1], res[2])
}

flagged_images <- actual %>% 
  filter(area > 2.5e05)

basedir <- "../../../h2_fec_images/h2_thresh_images/"

if (nrow(flagged_images) >= 1) {
  for (ii in 1:nrow(flagged_images)) {
    print(plot_jpeg(paste0(basedir, flagged_images$camera_id[ii])))
  }
}
```

## Prediction for all images

Linear model predicting egg count from area

```{r}
fm <- lm(handcount ~ area, data = actual)
```

```{r}
M$predicted_count <- predict(fm, newdata = M)
```

## Checks

Check these. They are handcounted but in the set of analyzed images.

```{r}
M %>% 
  filter(is.na(test_case)) %>% 
  filter(!is.na(handcount)) %>% 
  filter(handcount != "unassessable") %>% 
  filter(handcount != "unassigned") %>% 
  mutate(handcount = as.numeric(handcount)) %>% 
  select(camera_id, handcount, predicted_count) %>% 
  filter(!is.na(predicted_count))
```

## Some exploration

```{r}
ggplot(M, aes(predicted_count)) +
  geom_histogram(bins = 30)
```

Check high and low predicted eggs

```{r}
M %>% 
  select(camera_id, predicted_count) %>% 
  arrange(desc(predicted_count))
```

```{r}
M %>% 
  select(camera_id, predicted_count) %>% 
  arrange(predicted_count)
```

